VendorInvoice/Models/InvoicesViewModel.cs
using VendorInvoices.Entities;

namespace VendorInvoice.Models
{
    public class InvoicesViewModel
    {
        public Vendor ActiveVendor { get; set; }

        public List<Invoice> Invoices { get; set; }

        public Invoice NewInvoice { get; set; }

        public List<PaymentTerms> PaymentTerms { get; set; }

        public Invoice? ActiveInvoice { get; set; }

        public List<InvoiceLineItem> LineItems { get; set; }

        public InvoiceLineItem NewLineItem { get; set; }
        public char LowerBound { get; set; }
        public char UpperBound { get; set; }
    }
}

VendorInvoice/Models/VendorsViewModel.cs
using VendorInvoices.Entities;

namespace VendorInvoice.Models
{
    public class VendorsViewModel
    {
        public List<Vendor> Vendors { get; set; }
        public int LastDeletedVendorId { get; set; }
    }
}

VendorInvoice/Controllers/VendorInvoiceController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using VendorInvoice.Models;
using VendorInvoices.Entities;
using VendorInvoices.Services;

namespace VendorInvoice.Controllers
{
    public class VendorInvoiceController : Controller
    {
        private IVendorInvoiceManager _vendorInvoiceManager;
        public VendorInvoiceController(IVendorInvoiceManager vendorInvoiceManager)
        {
            _vendorInvoiceManager = vendorInvoiceManager;
        }

        [HttpGet("/vendors/{lowerBound}-{upperBound}")]
        public IActionResult GetAllVendorsAlphabetically(char lowerBound, char upperBound)
        {
            List<Vendor> vendors = _vendorInvoiceManager.GetAllVendorsAlphabetically(lowerBound, upperBound);
            ViewData["GroupSelected"] = $"{lowerBound}{upperBound}";
            return View("Vendors", vendors);
        }

        [HttpGet("/vendors/{id}/{lowerBound}-{upperBound}/edit-request")]
        public IActionResult GetVendorById(int id, char lowerBound, char upperBound)
        {
            Vendor vendor = _vendorInvoiceManager.GetVendorById(id);
            AddEditVendorViewModel editVendorViewModel = new AddEditVendorViewModel()
            {
                Vendor = vendor,
                LowerBound = lowerBound,
                UpperBound = upperBound
            };
            return View("EditVendor", editVendorViewModel);
        }

        [HttpPost("/vendors/edit")]
        public IActionResult ProcessEditRequest(AddEditVendorViewModel addEditVendorViewModel)
        {
            if (ModelState.IsValid)
            {
                _vendorInvoiceManager.UpdateVendor(addEditVendorViewModel.Vendor);
                return RedirectToAction("GetAllVendorsAlphabetically", new { lowerBound = addEditVendorViewModel.LowerBound, upperBound = addEditVendorViewModel.UpperBound });
            }
            else
            {
                ModelState.AddModelError("", "There were errors in the form - please fix them and try again.");
                return View("EditVendor", addEditVendorViewModel);
            }
        }

        [HttpGet("/vendors/{lowerBound}-{upperBound}/add-request")]
        public IActionResult GetAddVendorRequest(char lowerBound, char upperBound)
        {
            AddEditVendorViewModel addEditVendorViewModel = new AddEditVendorViewModel()
            {
                LowerBound = lowerBound,
                UpperBound = upperBound
            };
            return View("AddVendor", addEditVendorViewModel);
        }

        [HttpPost("/vendors/add")]
        public IActionResult AddNewVendor(AddEditVendorViewModel addEditVendorViewModel)
        {
            if (ModelState.IsValid)
            {
                _vendorInvoiceManager.AddNewVendor(addEditVendorViewModel.Vendor);
                return RedirectToAction("GetAllVendorsAlphabetically", new { lowerBound = 'a', upperBound = 'e' }); //!!!!!!!!!!!!!!!!!!!!!!!!!
            }
            else
            {
                ModelState.AddModelError("", "There were errors in the form - please fix them and try again.");
                return View("AddVendor", addEditVendorViewModel);
            }
        }

        [HttpGet("/vendors/{lowerBound}-{upperBound}/{vendorId}/invoice/{invoiceId}/line-itmes")]
        public IActionResult GetInvoicsByVendorId(int vendorId, int invoiceId, char lowerBound, char upperBound)
        {
            Vendor activeVendor = _vendorInvoiceManager.GetVendorById(vendorId);
            Invoice? activeInvoice;
            if (invoiceId == -1)
            {
                activeInvoice = _vendorInvoiceManager.GetFirstInvoiceByVendorId(vendorId);
            }
            else
            {
                activeInvoice = _vendorInvoiceManager.GetInvoiceById(invoiceId);
            }
            List<Invoice> invoices = _vendorInvoiceManager.GetInvoicesByVendorId(vendorId);
            List<PaymentTerms> paymentTerms = _vendorInvoiceManager.GetAllPaymentTerms();
            List<InvoiceLineItem> invoiceLineItems = new List<InvoiceLineItem>();
            if (activeInvoice != null)
            {
                invoiceLineItems = _vendorInvoiceManager.GetInvoiceLineItemsByInvoiceId(activeInvoice.InvoiceId);
            }
            InvoicesViewModel invoicesViewModel = new InvoicesViewModel()
            {
                ActiveVendor = activeVendor,
                ActiveInvoice = activeInvoice,
                Invoices = invoices,
                NewInvoice = new Invoice(),
                PaymentTerms = paymentTerms,
                LineItems = invoiceLineItems,
                LowerBound = lowerBound,
                UpperBound = upperBound
            };
            return View("Invoices", invoicesViewModel);
        }

        [HttpPost("/vendors/{lowerBound}-{upperBound}/{vendorId}/invoices/add")]
        public IActionResult AddInvoiceToVendorById(int vendorId, InvoicesViewModel invoicesViewModel, char lowerBound, char upperBound)
        {
            List<Invoice> invoices = _vendorInvoiceManager.GetInvoicesByVendorId(vendorId);
            invoicesViewModel.NewInvoice.VendorId = vendorId;
            invoices.Add(invoicesViewModel.NewInvoice);
            _vendorInvoiceManager.AddNewInvoice(invoicesViewModel.NewInvoice);
            return RedirectToAction("GetInvoicsByVendorId", new { vendorId = vendorId, invoiceId = invoicesViewModel.NewInvoice.InvoiceId, lowerBound = lowerBound, upperBound = upperBound });
        }

        [HttpPost("/invoices/{lowerBound}-{upperBound}/{id}/line-items/add")]
        public IActionResult AddInvoiceLineItemsByInvoiceId(int id, char lowerBound, char upperBound, InvoicesViewModel invoicesViewModel)
        {
            List<InvoiceLineItem> invoiceLineItems = _vendorInvoiceManager.GetInvoiceLineItemsByInvoiceId(id);
            invoicesViewModel.NewLineItem.InvoiceId = id;
            invoiceLineItems.Add(invoicesViewModel.NewLineItem);
            _vendorInvoiceManager.AddNewInvoiceLineItem(invoicesViewModel.NewLineItem);
            Invoice invoice = _vendorInvoiceManager.GetInvoiceById(id);
            return RedirectToAction("GetInvoicsByVendorId", new { vendorId = invoice.VendorId, invoiceId = id, lowerBound = lowerBound, upperBound = upperBound });
        }

        [HttpGet("/vendors/{lowerBound}-{upperBound}/{id}/delete")]
        public IActionResult ProcessDeleteRequestById(int id, char lowerBound, char upperBound)
        {
            var vendor = _vendorInvoiceManager.DeleteVendorById(id);

            HttpContext.Session.SetString("LastDeletedVendorId", id.ToString());

            TempData["LastActionMessage"] = $"The vendor \"{vendor.Name}\" was deleted.";

            return RedirectToAction("GetAllVendorsAlphabetically", new { lowerBound = lowerBound, upperBound = upperBound });
        }
        
        [HttpGet("/vendors/{lowerBound}-{upperBound}/{id}/undo-delete")]
        public IActionResult ProcessUndoDeleteRequestById(char lowerBound, char upperBound, int id)
        {
            _vendorInvoiceManager.UndoDeleteById(id);
            return RedirectToAction("GetAllVendorsAlphabetically", new { lowerBound = lowerBound, upperBound = upperBound });
        }
    }
}

VendorInvoice/Views/VendorInvoice/AddVendor.cshtml
@model AddEditVendorViewModel

@{
    ViewData["Title"] = "Add a new vendor";
}

<form asp-controller="VendorInvoice" asp-action="AddNewVendor" method="post" enctype="application/x-www-form-urlencoded">
    <partial name="_VendorFormsPartial" model="Model" />
    <button type="submit" class="btn btn-primary">Add</button>
</form>

@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

VendorInvoice/Views/VendorInvoice/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

VendorInvoice/Views/VendorInvoice/EditVendor.cshtml
@model AddEditVendorViewModel

@{
    ViewData["Title"] = "Edit vendor";
}

<form asp-controller="VendorInvoice" asp-action="ProcessEditRequest" method="post" enctype="application/x-www-form-urlencoded">
    <input type="hidden" asp-for="Vendor.VendorId" />
    <partial name="_VendorFormsPartial" model="Model" />
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

VendorInvoice/Views/VendorInvoice/Invoices.cshtml
@model InvoicesViewModel

@{
    ViewData["Title"] = "Invoices for " + Model.ActiveVendor.Name;

    string invoiceRowStyle = "";
}

<div class="container">
    <div class="row">
        <div class="col-sm">
            <h6 style="color:gray">Address: @Model.ActiveVendor.Address1 @Model.ActiveVendor.City</h6>
            <h6>Invoices</h6>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Invoice #</th>
                        <th>Due Date</th>
                        <th>Amount Paid</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var invoice in Model.Invoices)
                    {
                        if (Model.ActiveInvoice.InvoiceId == invoice.InvoiceId)
                        {
                            invoiceRowStyle = "table-primary";
                        }
                        <tr class=@invoiceRowStyle>
                            <td><a asp-asp-controller="VendorInvoice" asp-action="GetInvoicsByVendorId" asp-route-invoiceId="@invoice.InvoiceId">@invoice.InvoiceId</a></td>
                            <td>@invoice.InvoiceDueDate?.ToString("d")</td>
                            <td>@invoice.PaymentTotal?.ToString("c")</td>
                        </tr>
                        invoiceRowStyle = "";
                    }
                </tbody>
            </table>

            <form asp-controller="VendorInvoice" asp-action="AddInvoiceToVendorById" asp-route-vendorId="@Model.ActiveVendor.VendorId" asp-route-lowerBound="@Model.LowerBound" asp-route-upperBound="@Model.UpperBound" method="post" enctype="application/x-www-form-urlencoded">
                <div class="form-group">
                    <label asp-for="NewInvoice.InvoiceDate">Date:</label>
                    <input type="datetime" asp-for="NewInvoice.InvoiceDate" value="@DateTime.Today.ToShortDateString()" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="NewInvoice.PaymentTermsId">Terms:</label>
                    <select asp-for="NewInvoice.PaymentTermsId" class="form-control">
                        @foreach (var paymentTerms in Model.PaymentTerms)
                        {
                            <option value="@paymentTerms.PaymentTermsId">@paymentTerms.Description</option>
                        }
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Add Invoice</button>
            </form>
        </div>


        <div class="col-sm mt-n4">
            <a asp-controller="VendorInvoice" asp-action="GetAllVendorsAlphabetically" asp-route-lowerBound="@Model.LowerBound" asp-route-upperBound="@Model.UpperBound">Return to @Model.LowerBound.ToString().ToUpper()-@Model.UpperBound.ToString().ToUpper() vendors</a>
            <h6 style="color:gray">
                @{
                    string terms = "No due";
                    if (Model.ActiveInvoice != null)
                    {
                        terms = Model.ActiveInvoice.PaymentTerms.DueDays.ToString();
                    }
                }
                Terms: @terms Days
            </h6>
            <h6>
                @{
                    string invoiceId = "No line items";
                    if (Model.ActiveInvoice != null)
                    {
                        invoiceId = $"Line items for invoice #{Model.ActiveInvoice.InvoiceId}";
                    }
                }
                @invoiceId
            </h6>

            @{
                if (Model.ActiveInvoice != null)
                {
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var lineItem in Model.LineItems)
                            {
                                <tr>
                                    <td>@lineItem.Description</td>
                                    <td>@lineItem.Amount?.ToString("c")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    double? total = 0;
                    foreach (var lineItem in Model.LineItems)
                    {
                        if (lineItem.Amount != null)
                        {
                            total += lineItem.Amount;
                        }
                    }
                    <h6>Total: @total?.ToString("c")</h6>

                    <form asp-controller="VendorInvoice" asp-action="AddInvoiceLineItemsByInvoiceId" asp-route-id="@Model.ActiveInvoice.InvoiceId" asp-route-lowerBound="@Model.LowerBound" asp-route-upperBound="@Model.UpperBound" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group">
                            <label asp-for="NewLineItem.Description">Descripiton:</label>
                            <input type="text" asp-for="NewLineItem.Description" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="NewLineItem.Amount">Amount:</label>
                            <input type="text" asp-for="NewLineItem.Amount" class="form-control" />
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Add Line Item</button>
                    </form>
                }
            }
        </div>
    </div>
</div>

VendorInvoice/Views/VendorInvoice/Vendors.cshtml
@model List<Vendor>

@{
    ViewData["Title"] = "All Vendors Grouped";

    string btnAeStyle = "btn-light";
    string btnFkStyle = "btn-light";
    string btnLrStyle = "btn-light";
    string btnSzStyle = "btn-light";
    switch (ViewData["GroupSelected"])
    {
        case "ae":
            btnAeStyle = "btn-primary";
            break;
        case "fk":
            btnFkStyle = "btn-primary";
            break;
        case "lr":
            btnLrStyle = "btn-primary";
            break;
        case "sz":
            btnSzStyle = "btn-primary";
            break;
    }
}

@{
    if (ViewContext.TempData.ContainsKey("LastActionMessage"))
    {

        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span>
                @TempData["LastActionMessage"]
                <a asp-controller="VendorInvoice" asp-action="ProcessUndoDeleteRequestById" asp-route-lowerBound="@ViewData["GroupSelected"].ToString()[0]" asp-route-upperBound="@ViewData["GroupSelected"].ToString()[1]" asp-route-id="@Context.Session.GetString("LastDeletedVendorId")">Undo</a>
                this delete.            
            </span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
}

<a asp-controller="VendorInvoice" asp-action="GetAddVendorRequest" asp-route-lowerBound="@ViewData["GroupSelected"].ToString()[0]" asp-route-upperBound="@ViewData["GroupSelected"].ToString()[1]">Add a vendor</a>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var vendor in Model)
        {
            if (vendor.IsDeleted == false)
            {
                <tr>
                    <td>@vendor.Name</td>
                    <td>@vendor.Address1 @vendor.Address2, @vendor.City, @vendor.ProvinceOrState</td>
                    <td>
                        <a asp-controller="VendorInvoice" asp-action="GetInvoicsByVendorId" asp-route-vendorId="@vendor.VendorId" asp-route-lowerBound="@ViewData["GroupSelected"].ToString()[0]" asp-route-upperBound="@ViewData["GroupSelected"].ToString()[1]" asp-route-invoiceId="-1">Invoices</a>
                        <span class="mix">|</span>
                        <a asp-controller="VendorInvoice" asp-action="GetVendorById" asp-route-id="@vendor.VendorId" asp-route-lowerBound="@ViewData["GroupSelected"].ToString()[0]" asp-route-upperBound="@ViewData["GroupSelected"].ToString()[1]">Edit</a>
                        <span class="mix">|</span>
                        <a asp-controller="VendorInvoice" asp-action="ProcessDeleteRequestById" asp-route-lowerBound="@ViewData["GroupSelected"].ToString()[0]" asp-route-upperBound="@ViewData["GroupSelected"].ToString()[1]" asp-route-id="@vendor.VendorId">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<a asp-controller="VendorInvoice" asp-action="GetAllVendorsAlphabetically" asp-route-lowerBound="a" asp-route-upperBound="e" class="btn @btnAeStyle">A-E</a>
<a asp-controller="VendorInvoice" asp-action="GetAllVendorsAlphabetically" asp-route-lowerBound="f" asp-route-upperBound="k" class="btn @btnFkStyle">F-K</a>
<a asp-controller="VendorInvoice" asp-action="GetAllVendorsAlphabetically" asp-route-lowerBound="l" asp-route-upperBound="r" class="btn @btnLrStyle">L-R</a>
<a asp-controller="VendorInvoice" asp-action="GetAllVendorsAlphabetically" asp-route-lowerBound="s" asp-route-upperBound="z" class="btn @btnSzStyle">S-Z</a>